export const PORTFOLIO = "https://maddie-portfolio.s3.amazonaws.com/portfolio/Jan+2024_Full+Portfolio.pdf"

export const CHAIN_OF_ROCKS = {
  name: "Chain of Rocks Bridge",
  header1: "Mississippi River, St. Louis / Critic Anna Ives",
  header2: "Washington University in St. Louis / 2017",
  text: [
    "Located at the intersection of both natural and synthetic infrastructures, the steel truss Chain of Rocks Bridge's 22-degree bend is used in this project as a tool to re-imagine the American hostel. Given pathway variability, which route does naturally flowing water traverse?",
    "Multiple twine, wire, and wood root material studies were used to document and quantify the movement of water with radial graphs. Graphed in relation to dampness, the data verified that water flows on the path of least resistance, from high ground to low ground. The central stairway operates as the tap root while the path of least resistance leads one down to the communal living space, diverging from the ascending and safely secluded private bedroom path."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/image_order/01_FIRST+IMAGE+PLS.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/image_order/7.jpg"
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/chain_of_rocks/title_image/No+background+bridge.png"
}

export const CONTAINER_AND_CONTAINED = {
  name: "Container and Contained",
  header1: "Los Angeles, CA / Critic Lawrence Blough",
  header2: "Washington University in St. Louis / 2018",
  text: [
    "Clusters of private units extend above shared community space below, permitting groups of similar minded digital nomads to live together in collaborative vertical neighborhoods. A web of interstitial space connects patios, balconies, and stairways that extend over the open atrium to support networking and a variety of entry and exit points to the building.",
    "Shades of privacy flow from the publicly accessible lobby on the lower level to all-embracing sheltered privacy in one's 10'x10' unit. This flexibility accommodates changing live and work situations, allowing residents to occupy the building longer and therefore in a more sustainable manner."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/8.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/9.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/10.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/12.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/13.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/15.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/16.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/17.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/18.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/19.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/20.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/21.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/image_order/22.jpg"
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/container_and_contained/title_image/4.jpg"
};

export const CRATER = {
  name: "Crater",
  header1: "Partner Tanil Raif / Critic Wenjing Huang and Li Hu, OPEN Architects",
  header2: "Harvard GSD / 2024",
  text: [
    "In this project, we invite connection between human and non-human, academia and civility to shape optimistic realities. We propose a design school that confronts the didactic relationship between teachers and pupils and design education's typical lack of contact with the public. We propose a living museum: A design education that encourages contact and collaboration with local ecologies, community, and industry.",
    "The present-day site consists of reclaimed land with a high water table. We suggest converting the site back into natural wetland to allow underground connection between adjacent bodies of water. The valley has a smaller footprint than a traditional structure to address the need for the wetlands will take over with increased flooding. Our intent is not to control but create a backdrop for nature to takeover.",
    "Due to the suitable climate, the plan is largely open-air with a light aluminum tubing façade. Filleted walls are softer at the perimeter and become more orthogonal towards the center of the plan. The exhibition spaces are publicly accessible, with the pin-up spaces wrapping the nooks in circulation space The library, auditorium, and community room jut out of the volume, visible from the exterior, to suggest their public-oriented facilities. Art disciplines look at one another across the valley, intentionally oriented so social collaboration may spill out onto balconies and intersect in the exhibition tissue."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/1.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/8.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/9.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/15.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/16.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/17.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/18.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/19.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/20.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/21.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/22.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/23.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/24.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/25.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/26.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/27.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/28.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/29.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/30.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/31.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/32.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/33.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/34.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/40.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/image_order/41.jpg"
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/crater/title_image/bowl+render.png"
};

export const GIFT_ECONOMY = {
  name: "Gift Economy",
  header1: "Core III / Critic Grace La",
  header2: "Harvard GSD / 2022",
  text: [
    "This urban distillery grapples onto slowness and reciprocity of plant life and bourbon production to create a continuous sharing of wealth. The curved walls slow you down and encourage distraction, exploration, and curiosity, atomizing away from the central nodes of production to line the path back into the arboretum, functioning as smaller tasting pods down the human scale of a table or stool.",
    "To feed back into the system, the by-product of corn, rye, and sugar following the fermentation process and is composted below the building and the nitrogen-rich liquid is deposited on site. The heat from the composting system works much like a geo-thermal heat pump. Coils sit under the compost and heat the air that circulates through spaces that may be enjoyed year-round. By resisting the temporal field of vision and the pressure to improve quickly, we create better product—better bourbon and better landscape."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/01_first Image.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/1.2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/1.3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/8.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/9.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/15.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/16.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/17.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/18.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/19.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/20.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/21.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/22.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/23.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/24.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/25.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/26.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/27.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/28.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/29.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/30.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/31.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/32.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/33.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/34.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/35.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/image_order/37.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/gift_economy/title_image/title+image.jpg"
}

export const HEWITT = {
  name: "Professional Work / HEWITT Architects",
  header1: "Seattle, WA / 2019-2021",
  header2: "",
  text: [
    "At HEWITT Architects, I was responsible for Seattle Design Review board packages, design development and construction phase detail documentation, feasibility and land use studies, Enscape renderings, and physical model iteration to communicate essential messaging to City and Client groups for high-rise residential buildings.",
    "I found the most valuable design happened within walking distance of our office, including in districts where my research was presented at community outreach meetings to promote accommodation of historical fabric."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/01.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/02.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/03.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/05.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/07.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/15.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/16.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/17.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/18.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/19.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/20.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/21.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/22.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/23.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/24.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/25.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/26.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/27.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/hewitt/title.jpg"
};

export const HOUSE_OF_INVERSIONS = {
  name: "House of Inversions",
  header1: "Core 1 / Critic Marina Correia",
  header2: "Harvard GSD / 2021",
  text: [
    "What dictates how we live beyond the physical? In this project, I investigated conditions of the immaterial in the domestic. I considered how shadows, occupying the site, and material inconsistencies may invite users to seek varying levels of exposure, both in terms of light and social experiences. The resulting structure creates different degrees of interiority, suiting two contrasting living experiences.",
    "The upper unit's open-air patio and wide glazing fosters a sense of display, disclosure, exhibition, and uncovering. The second level links high and low exposure through a controlling screen—a demising wall—between user and the outdoors. Fully inserted into the topography, the lower level's highly controlled aperture establishes a house of inversions."
    ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/01_First image.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/13.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/14.png",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/house_of_inversions/title_image/Blue+and+Pink.jpg"
};

export const JUMP_CUT = {
  name: "Jump Cut: Coherence in Discontinuities",
  header1: "Core 1 / Critic Marina Correia",
  header2: "Harvard GSD / 2021",
  text: [
    "Tasked with connecting two seemingly incompatible sections within one building, I designed a coherent exterior envelope that accommodates incongruent interior characters.", 
    "Two arms branch from the pivot point that connects the two sections, opening into a void that serves as a theater. The vertical access is located at the hinge, while audience functions extrude in opposite direction from the void. The massing suggests a consistency, but offers several open programmatic possibilities and two-way observation across angles, disciplines, and uses."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/1.5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/2.5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/3.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/3.5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/05.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/07.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/15.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/16.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/17.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/image_order/18.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/jump_cut/title_image/11.jpg",
}

export const LIVING_INTERSECTION = {
  name: "Living Intersection",
  header1: "Dutchtown, St. Louis / Critic Linda Samuels",
  header2: "Washington University in St. Louis / 2017",
  text: [
    "The intense, multi-lane traffic knot in Dutchtown, St. Louis is a collision of speeds, modalities, land uses, people, waste, cultures, historical wealth, and future opportunity. The studio analyzed two government initiatives—EPA's Environmental Justice Collaborative Problem-Solving grant program and the city's multi-billion dollar Metrolink expansion—to propose systems that reduce illegal dumping and improve community capacity through strategies of education, action, and creative upcycling.", 
    "Incorporating the knowledge gained from engagement with neighbors and businesses, the new station for the Metrolink stop responds to the waste reuse and political opportunities found on the site. The proposed design spurs economic growth through formal and informal opportunity as seen within the sheltered local vendor arcade.",
],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/2.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/3.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/8.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/9.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/image_order/12.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/living_intersection/title_image/1.jpg",
};

export const MDEAS = {
  name: "Professional Work / MdeAS Architects",
  header1: "NYC / 2022",
  header2: "",
  text: [
    "I developed interior and exterior renderings, material curation, facade studies, and detail construction documents for adaptive re-use iconic projects such as the Lipstick Building, Studio 54, and Penn 2."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/01.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/02.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/03.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/03.1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/03.2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/03.3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/05.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/07.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/image_order/10.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/mdeas/title/title.jpg",
}

export const PATTERNS_IN_NATURE = {
  name: "Patterns in Nature: Topographic Extensions",
  header1: "Forest Park, St. Louis / Critic Elisa Kim",
  header2: "Washington University in St. Louis / 2015",
  text: [
    "This study explored the fluctuating movement in the texture of a peeling Birch Tree. The pattern of horizontal movement is emphasized though the varied, accentuated textures between each strip of bark. Hand drawings of differing line weights, distinct designs, and solely linear marks indicate the separation of textures to movement across the page.",
    "The wire module weaves throughout the basswood topography to create another traveling system. The wire swells with density at each point of contact, then disperses to imitate motion."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/8.JPG",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/9.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/Swirling+Triangle.png",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/patterns_in_nature/image_order/1.jpg",
}

export const POWER_ENERGY = {
  name: "Power + Energy: Mapping the Thickened Ground of Labor",
  header1: "Partner Tanil Raif / Critic Rose Monacella and Glynwood Center for Food and Regional Farming",
  header2: "Harvard GSD / 2024",
  text: [
    "What evidence tells us iron ore is energy? Who claimed this matter is inert, and can be readily commoditized and sold? When does the movement of 'becoming' a 'productive' material begin and end? What other sources of energy have always been embedded in the Putnam County landscape, beyond timber, charcoal, and iron ore?",
    "In the 1800s, Coldspring, NY thrived as a hub for profitable iron mining and smelting in Putnam County, boasting high-quality iron ore sought after nationwide. Today, Glynwood Center is a non-profit farming and livestock operation dedicated to the mission of researching climate-smart agriculture.",
    "I aim to align events, infrastructures, histories, and values to expose how power structures determined iron ore was an energy source that could provide and prove the need for the war engine. I hope the alignment of time and place leads to new modes of perception, reading, knowing, or experience to interrupt popular ideas of extraction, consumption, and waste."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/image_order/8.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/power_energy/title_image/cropped.jpg",
}

export const PUBLIC_PALACE = {
  name: "Public Palace",
  header1: "Core II / Critic Emmett Zeifman",
  header2: "Harvard GSD / 2022",
  text: [
    "Entirely massive yet accessible, alien in form yet child-like enough to inhabit the collective imagination, this public palace suggests mystery and play to challenge what a civic building should be. This proposal responds to the contextual datum of the towering, neighboring highway bridge and the smaller scale school by adapting the mass into sections to create a stepping of architectural scale and use.",
    "The idiosyncratic moments are unified through a homogenous concrete massing on top of playful green steel. At the street level, nothing but the leg-like cores touch the ground. Climbing, sliding, viewing, adventuring occurs this hyper-open underbelly. A dramatic stair ascends onto the second level theater, open at both ends for views of sunrise and sunset. Above, a village of tighter program serves as space for learning, practice, and rehearsal. Specific balconies orient views towards downtown Boston."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/01.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/01.2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/02.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/03.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/3.5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/4.5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/05.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/5.1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/5.2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/5.3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/5.4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/5.5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/07.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/15.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/16.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/18.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/19.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/20.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/21.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/22.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/image_order/23.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/public_palace/title_image/01+White+no+shadow.jpg"
}

export const REST_STOP_REVISITED = {
  name: "Rest Stop Revisited",
  header1: "Duluth, Minnesota / Critic Jennifer Yoos",
  header2: "Washington University in St. Louis / 2019",
  text: [
    "Informed by its dramatic, forested context as well by its rural context above the city of Duluth, the rest stop integrates practical programs with play. Play occupies the landscape. Pedestrian paths are lined with inhabitable concrete walls that vary in height, density, and utility.",
    "They may serve as playground infrastructure, punctured with holes and foot holds, or act as a guidance tool along hidden trails. They curve seamlessly into the buildings to create an effortless transition between exposed path and shelter, operating as a form of pre-cast cladding shading."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/01_First image.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/1.2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/8.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/image_order/10.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/reststop_revisited/title_image/white+model+1.jpg",
};
  
export const SENSING_TEXTURE = {
  name: "Sensory Inhabitation",
  header1: "Digital Media: Models / Critic Hyojin Kim",
  header2: "Harvard GSD / 2022",
  text: [
    "A jackfruit skin was 3D scanned, pressed in agar to produce a silicone mold, and then re-cast using textures such as fabric and soap. The representation is diminished, simplified tectonic copy of the original, but it grapples with certain qualities (the cellular tessellations) and amplifies them beyond what reality allows.",
    "This project proposes a sensorially rich domestic environment where different textures and materials begin to suggest different zones of inhabitation and function, and surfaces can provide haptic feedback to the occupant. For example, one can imagine lounging on a soft floor or gaining comfort from a wall that hugs you back."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/01.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/02+jackfruit+scan.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/03_3+skins+in+a+row.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/04_Scanned+skin+raw.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/05_Silicone+making.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/06.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/07.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/10.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/11.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/12.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/15.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/16.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/17.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/18.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/19.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/20.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/21.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/22.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/23.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/24.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/25.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/26.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/27.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/28.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/29.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/30.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/31.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/32.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/image_order/33.gif",
  ],
  thumbnail:  "https://maddie-portfolio.s3.amazonaws.com/architecture/sensing_texture/title_image/01.jpg",
}

export const SIDEWALK_STUFF = {
  name: "Sidewalk Stuff",
  header1: "Partner Randy Crandon / Critic Jenny French",
  header2: "Harvard GSD / 2023",
  text: [
    "This cooperative housing proposal challenges the illusion of self-sufficient private accumulation by promoting material sharing on an infrastructural scale, redirecting waste streams, and fostering a circular economy. It acknowledges the typologies of suburban sprawl, such as the American suburban home and office park building, which have shaped domesticity and comfort.",
    "The site features four vacant office buildings surrounded by parking lots and adjacent homes. Characters representing American domesticity and comfort were identified as:  1. The Self Storage Warehouse, 2. The Scrap and Salvage yard, 3. The Big Box Store, and 4. The Distribution Center. Each office building is recast as one of these characters, inheriting plan and infrastructural logistics. Within these satellite collectives, informal markets, like online buy-nothing groups, extend the lifespan of goods and promote communal wealth.",
    "Urbanistically, a field strategy is employed where row houses fill the spaces between buildings to intensify density while maintaining suburban tropes. Residential units are modular, modest, and light – manufactured on-site in a variety of configurations for varying family structures. By reframing domestic life through shared goods, American consumerism is slowed, reordered, and contained. This approach prevents material and energy over-consumption while cultivating invaluable human relationships and purpose.",
    "Winner of the <a href=\"https://www.gsd.harvard.edu/project/2023-clifford-wong-prize-in-housing-design-randy-crandon-and-maddie-farrer/\">Harvard GSD 2023 Clifford Wong Prize in Housing.</a>"
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/8.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/9.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/15.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/16.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/17.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/18.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/19.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/20.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/21.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/22.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/23.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/24.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/25.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/26.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/27.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/28.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/29.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/30.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/31.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/32.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/33.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/34.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/35.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/36.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/37.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/38.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/39.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/40.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/image_order/41.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/sidewalk_stuff/title_image/Field+of+Housing.jpg",
}

export const SOULARD_MARKETPLACE = {
  name: "Soulard Marketplace",
  header1: "Soulard, St. Louis / Critic Nathaniel Elberfeld",
  header2: "Washington University in St. Louis / 2017",
  text: [
    "The North Soulard Garden and Marketplace is an seamless extension of the natural topography that creates a threshold between city and garden. The structure provides a legible point of arrival and orientation at the welcoming patio entrance, rising into a three-dimensional green continuation of the path connecting Northern and Southern communities.",
    "To provide suitable living conditions for the Maranta Leuconeura within cold Midwestern Missouri, a plexiglass container encloses the plant to produce a more humid environment to mimic its native tropical habitat while beads of condensation collect on the folding apparatus and drip down to the roots, similar to the natural transfer of dewdrops downward upon the Maranta's leaves."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/01.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/02.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/03.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/05.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/06.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/07.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/11.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/13.png",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/image_order/14.png",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/soulard_marketplace/title_image/Hand+drawing+of+leaves.png"
}

export const RESHAPING_REMNANTS = {
  name: "Reshaping Remnants: Architecture's Role in Post-Mining Rehabilitation",
  header1: "Breathitt County, KY / Instructed by Laura Lengnick, Edward Eigen, Toshio Mori, John May, Eric Höweler",
  header2: "Harvard University Graduate School of Design / 2024",
  text: [
    "I explored the reuse of waste stone from strip mining to create ecologically and culturally restorative designs, drawing parallels between the labor-intensive processes of repairing mined landscapes and traditional quilting, and involving local communities in hyper-local collaboration to heal and transform desolate sites into valuable public spaces.",
    "I ask how humans should engage with this landscape of desolation using design. Geometries at mining sites are not accidental. The land, already made by human intervention, can be made into valuable spaces for human and non-human agents. Certain forms are effective at different scales, as polarizing minute stone construction detail may inform the larger project. To represent is to have an attitude towards the site. How did certain ways of representation lead to a certain way of environmental management?"
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_8.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_9.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_13.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_14.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_15.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_16.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_17.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_18.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_19.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_20.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_21.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_22.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_23.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_24.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_25.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_26.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_27.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_28.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_29.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_30.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_31.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_32.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_33.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_34.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_35.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_36.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_37.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_38.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_39.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_40.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_41.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_42.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_43.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_44.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_45.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_46.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_47.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_48.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_49.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_50.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_51.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_52.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_53.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_54.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_55.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_56.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_57.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_58.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_59.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_60.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_61.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_62.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_63.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_64.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_65.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_66.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_67.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_68.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_69.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_70.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_71.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_72.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_73.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_74.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_75.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_76.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_77.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_78.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_79.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_80.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_81.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/image_order/Reshaping+Remnants_82.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/reshaping_remnants/title_image/title.jpg"
}

export const URBAN_CHAPEL = {
  name: "Urban Chapel",
  header1: "Concordia Park, St. Louis / Critic Emiliano Lopez",
  header2: "Washington University in St. Louis / 2016",
  text: [
    "The Urban Chapel is a non-denominational space that explores the symbolic and spatial qualities of light. It is a spiritual space open to all practices of religion and meditation. Large, surrounding walls rise out of the land to block the rising sun's rays from the east and the setting sun's rays from the west. The circular peaks align to direct light linearly from above into the central space, allowing the sanctuary to both glow and inhibit the passage of light.",
    "The spiraling layers suggest a path but do not impose. One may walk in a circular passageway through the crossing layers before reaching the heart of the structure. The central private, enclosed, and light-filled dome instills a spiritual sense in the user as the beam of light from above fills the space with a warm glow."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/6.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/7.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/8.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/9.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/10.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/11.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/12.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/image_order/13.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/urban_chapel/title_image/hand+sketch.jpg",
}

export const SEAGRAM = {
  name: "New Skin for Seagram",
  header1: "Seagram Building, NY / Critic Eric Höweler",
  header2: "Harvard Graduate School of Design / Spring 2023",
  text: [
    "This proposal addresses David Barber's question, \"What is architecture after comfort?\" by replacing the Seagram building's thin curtain wall with a visible conversation with changing seasons. Rather than hide conditioning systems, placing the thermal stack effect on display is an expression of collective will to make our structures work in tandem with the unpredictable climate.",
    "Like the Seagram building, exterior glass panels extend unbroken floor-to-ceiling. In this proposal, the glass is still positioned within the structural frame and provides a similar technological appeal but becomes energy efficient through passive heating and cooling stack effect methods.",
    "This proposed double-skin curtain wall system consists of an outer wall of monolithic glass in a prefabricated unit system and an inner wall of insulating glass in a stick system, separated by an air space. This permits enough room for cleaning and performs as an air-extract duct, reducing the back-up mechanical ventilation to a minimum."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/seagram/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/seagram/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/seagram/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/seagram/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/seagram/image_order/5.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/seagram/image_order/6.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/seagram/title/title.jpg",
}

export const THESIS_PREP_BOOK = {
  name: "Thesis Prep Book",
  header1: "Breathitt County, KY / Instructed by Laura Lengnick, Edward Eigen, Toshio Mori, John May, Eric Höweler",
  header2: "Harvard University Graduate School of Design / 2024",
  text: [
    "Geometries at mining sites are not accidental. Landform, already made by human intervention, can be made into valuable spaces for human and non-human agents. How do we inhabit the parameters of a desolate moonscape without reinforcing the boundaries that the mining economy has established? By exploring hyper-local construction with repurposed stone, I ask how we may re-stitch discarded \"waste\" to repair relationship.",
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/thesis_prep_book/image_order/1.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/thesis_prep_book/image_order/2.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/thesis_prep_book/image_order/3.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/thesis_prep_book/image_order/4.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/thesis_prep_book/image_order/5.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/thesis_prep_book/title_image/title.jpg",
}

export const MOVING_STONE = {
  name: "Stone Moving, Moving Stone",
  header1: "Melides, Portugal / Critic Lina Ghotmeh",
  header2: "Harvard University Graduate School of Design / 2024",
  text: [
    "This elderly housing project embraces the sacred slow aspects of existence within natural spaces. I sought to imbue structures with the fluidity of time, incorporating the cyclical processes of design, construction, and inhabitation.",
    "I twisted a long stick of graphite, placing fabric behind the paper to let the softness of impact direct the weight, then used the same twist of my wrist to rotate model stones through a wire cutter. Portuguese stone erodes from the sea air in a relational and dynamic phenomenon; it is not static in time or space. It is a reminder that time goes on, and in a lovely way, will persist.",
    "Blocks of quarried limestone are discarded due to imperfections. To create the most economic, least-processed construction path, the \"waste\" stones are stacked and wire-cut in three dimensions. Vibrations of friends and life cut through the linear arrangement. Inhabiting the building is a story of discovery, as peeks of nature inhabit nooks between the different programs, activity and rest."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_01.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_02.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_03.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_05.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_07.gif",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_010.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_011.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_012.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_013.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_014.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_015.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_016.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_017.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_018.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_019.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_020.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_021.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_022.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_023.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_024.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_025.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_026.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_027.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_028.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_029.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_030.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_031.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_032.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_033.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_034.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_035.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_036.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_037.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_038.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_039.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_040.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_041.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_042.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_043.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_044.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_045.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_046.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_047.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_048.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_049.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_050.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_051.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_052.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_053.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_054.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_055.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_056.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_057.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_058.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_059.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_060.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_061.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_062.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_063.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_064.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_065.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_066.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_067.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_068.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_069.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_070.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_071.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_072.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_073.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_074.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_075.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_076.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_077.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_078.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_079.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_080.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_081.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_082.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_083.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/image_order/Stone_084.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/moving_stone/title_image/title.jpg",
}

export const IRREGULAR_STONE_JIG = {
  name: "Irregular Stone Jig",
  header1: "Partner Tanil Raif / Critic Jonathan Grinham",
  header2: "Harvard GSD / 2024",
  text: [
    "This project explores the negotiation of irregular shapes with controlled geometry. The research aims to address the issue of \"waste\" by designing a custom jig to securely hold and shape off-cut rocks for integration into standard construction processes.",
    "A toolpath in Rhino projected a rising spiral between rocks, with parametric controls enabling precise robot movements, including under rock ledges. This process blends robotic precision with human creativity for architectural applications, showcasing a hyper-local collaboration.",
    "To 3D print clay between irregular rocks using the IRB140 robotic arm, rocks were 3D scanned, attached to a reference plate, and treated as a single object."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image01.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image1.5.mp4",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image02.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image03.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image05.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image07.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image010.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image011.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image012.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image013.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/image_order/Image014.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/irregular_stone_jig/title_image/title.png"
}

export const CUSTOM_SANDSTONE_MORTAR = {
  name: "Custom Sandstone Mortar",
  header1: "Partner Tanil Raif / Critic Jonathan Grinham",
  header2: "Harvard GSD / 2024",
  text: [
    "Strip mining involves blowing off limestone, siltstone, sandstone, and other \"overburden\" rocks to access economically valuable seams of coal. Older rocks like gray unweathered sandstone hinders soil development and tree growth. Younger red sandstone crumbles more easily, making it useful as mortar when pulverized."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image0.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image02.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image03.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image05.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image07.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image010.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image011.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image012.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/image_order/Image013.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/custom_sandstone_mortar/title_image/title.png"
}

export const PRINTING_SPACES_IN_STONE = {
  name: "Printing Spaces in Stone",
  header1: "Partner Tanil Raif / Critic Jonathan Grinham",
  header2: "Harvard GSD / 2024",
  text: [
    "The proposal for 3D printing sandstone mortar between irregular unweathered gray sandstone rocks transforms into an architectural reality, using a custom toolpath to explore spatial considerations and enable innovative applications. This process represents a hyper-local collaboration between robots and humans, with robots excelling at precision and heavy-lifting, while humans bring creativity and adaptability to site-specific tasks, such as designing window and door placements. The mortar serves as a pedestal for stone, poetically elevating massive, once-discarded materials into something beautiful and celebrated, reframing our perception of the landscape and transforming nuisance waste into a valued resource."
  ],
  images: [
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image0.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image02.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image03.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image04.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image05.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image06.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image07.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image08.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image09.jpg",
    "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/image_order/Image010.jpg",
  ],
  thumbnail: "https://maddie-portfolio.s3.amazonaws.com/architecture/printing_spaces_in_stone/title_image/title.jpg"
}

